---
- name: Ping google.com and parse latency
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run ping command
      command: ping -c 3 google.com
      register: ping_result
      ignore_errors: yes

    - name: Extract the avg latency from final line
      set_fact:
        ping_avg_latency: "{{ ping_result.stdout | regex_search('= (\\S+)/(\\S+)/(\\S+)/(\\S+) ms', '\\2') | default('N/A') }}"
      when: ping_result.rc == 0

    - name: Show results
      debug:
        msg: >
          Ping to google.com {{ 'failed' if ping_result.rc != 0 else 'succeeded' }}.
          Average latency: {{ ping_avg_latency }} ms
